DELETE FROM PUBLIC.RATING;
DELETE FROM PUBLIC.GENRE;

INSERT INTO PUBLIC.GENRE (NAME, ID) VALUES('Комедия', 1);
INSERT INTO PUBLIC.GENRE (NAME, ID) VALUES('Драма', 2);
INSERT INTO PUBLIC.GENRE (NAME, ID) VALUES('Мультфильм', 3);
INSERT INTO PUBLIC.GENRE (NAME, ID) VALUES('Триллер', 4);
INSERT INTO PUBLIC.GENRE (NAME, ID) VALUES('Документальный', 5);
INSERT INTO PUBLIC.GENRE (NAME, ID) VALUES('Боевик', 6);

INSERT INTO PUBLIC.RATING (NAME, ID) VALUES('G', 1);
INSERT INTO PUBLIC.RATING (NAME, ID) VALUES('NC_17', 5);
INSERT INTO PUBLIC.RATING (NAME, ID) VALUES('PG', 2);
INSERT INTO PUBLIC.RATING (NAME, ID) VALUES('PG_13', 3);
INSERT INTO PUBLIC.RATING (NAME, ID) VALUES('R', 4);
